spring.application.name=ProyectoTriageSolicitud

# Puerto del servidor
server.port=8080

# Configuración de base de datos
spring.datasource.url=jdbc:postgresql://ep-royal-darkness-amlnznxq-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IGRd0hXsEHU5
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Formatear SQL en consola
spring.jpa.properties.hibernate.format_sql=true

# Hikari connection pool
spring.datasource.hikari.maximum-pool-size=10
